# config.yml
settings:
  concurrency: 50  # High concurrency for faster processing
  fetchTimeout: 3000  # Timeout for fetching M3U files
  linkCheckTimeout: 2000  # Timeout for checking link activity
  batchSize: 100  # Number of links to check in a single batch
  outputDirPrefix: SpecialLinks  # Base name for output directories/files
  channelsPerFile: 2000  # Maximum number of channels per file

urls:
- http://stb.velocity.watch:8080/get.php?username=Naverah&password=Home2&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=melodyg&password=uQnLQnTkRj&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=Landlord1&password=8132793342&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=ElizabethG2023&password=4tQeHW48DWBg&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=September2024e&password=Touchdown&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=2055676975&password=MAAvrCmWZ8FZ&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=1915WMAIN&password=WqSc8ZaqdG&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=7062390861&password=ksAGBaT29HEb&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=Thomaswashington&password=ZEQpCYLuBm&type=m3u_plus
- http://stb.velocity.watch:8080/get.php?username=ksabrina&password=ouyZTyk75O&type=m3u_plus
- http://nocable.cc:8080/get.php?username=fNeb6z&password=084603&type=m3u_plus
- http://matrivagoweb.xyz:2095/get.php?username=GROUP3411&password=123456&type=m3u
- http://directo.ddns.me:33200/get.php?username=stkjamna&password=7833&type=m3u
- http://imaxplay.net:2082/get.php?username=GerardoRamirez22&password=VMZRD&type=m3u
- http://nocable.cc:8080/get.php?username=ez4evr@icloud.com&password=7Qw7aHb4x3&type=m3u_plus
- http://nocable.cc:8080/get.php?username=sFFAV3&password=440174&type=m3u_plus
- http://nocable.cc:8080/get.php?username=u6cJ2x&password=222188&type=m3u_plus
- http://nocable.cc:8080/get.php?username=wY457J&password=162045&type=m3u_plus
- http://nocable.cc:8080/get.php?username=droseburough@gmail.com&password=droseburough@2023&type=m3u_plus
- http://istar1.pro:80/get.php?username=8546120&password=24193154392606&type=m3u_plus
- http://hdhd.tk:80/get.php?username=281123&password=281123&type=m3u
- http://hdhd.tk:80/get.php?username=b0186&password=8018&type=m3u 
- http://tvmate.icu:8080/get.php?username=0n8u9R&password=169324&type=m3u 
- http://vocotv.pro:80/get.php?username=Nancy&password=Nancy1&type=m3u_plus
- http://bstv.online:8080/get.php?username=2aeg04&password=5878546467h&type=m3u 
- http://tv2watch.icu:8080/get.php?username=DRIPTV0021&password=TDi6gVVnTs&type=m3u
- http://pressrle.lat/get.php?username=Tx7UWc&password=6cwZxz&type=m3u 
- http://xdgo.live:8080/get.php?username=HugoNavarroArredondo&password=t1t2t3t4&type=m3u 
- http://filinta.eu/get.php?username=RXDSFQt8aK&password=cPLhPjAg4B&type=m3u 
- http://premium2.ottpro2.org:8789/get.php?username=feuvrier&password=3657255&type=m3u 

  # Add more URLs here (up to 100)
